// <auto-generated />
using System;
using FitnessProgressTracker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FitnessProgressTracker.Migrations.ExerciseTracker
{
    [DbContext(typeof(ExerciseTrackerContext))]
    [Migration("20190403182539_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FitnessProgressTracker.Models.Exer_tracker", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DOB");

                    b.Property<string>("exercise");

                    b.Property<int>("load");

                    b.Property<int>("repeats");

                    b.Property<int>("time_between");

                    b.HasKey("ID");

                    b.ToTable("Exer_tracker");
                });
#pragma warning restore 612, 618
        }
    }
}
